# TODO: build & deploy to production via Ansible

stages:
  - test

unit test:
  image: node:14.16.1-buster
  stage: test
  script:
    - apt update && apt install -y –no-install-recommends python3
    - npm install
    - npm run test
