stages:
  - test
  - build
  - docker

image: node:14.16.1-buster

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - /root/.npm/

before_script:
  - npm ci --cache /root/.npm --prefer-offline

unit-test:
  stage: test
  script:
    - npm run test

build-site:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist
    expires_in: 1 week

build-image-and-upload:
  stage: docker
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
