---
- name: Deploy NOJ frontend to production
  hosts: all
  gather_facts: no
  
  tasks:
    - name: Ensure services directory
      file:
        path: /home/gitlab-runner/services
        state: directory

    - name: File Synchronisation
      ansible.posix.synchronize:
        src: ./
        dest: /home/gitlab-runner/services/noj-frontend
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=.vscode"
          - "--exclude=logs/*"

    - name: Ensure traefik network
      community.general.docker_network:
        name: traefik
        state: present
        
    - name: Create and start services
      community.docker.docker_compose:
        project_src: /home/gitlab-runner/services/noj-frontend
        recreate: always
        remove_orphans: yes
      register: output

    - ansible.builtin.debug:
        var: output
